#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t siprit"

$L " __   __  °  __  ° ___    __   __      ";
$L "|__  |__| | | _| |  |  _ | _| |  | |\/|";
$L " __| |    | |  \ |  |    |  \ |__| |  |";
$L "Welcome to Android `getprop ro.build.version.release` / Spirit-Rom-`getprop ro.spirit.version`";
