add_lunch_combo spirit_d2lte-userdebug
add_lunch_combo spirit_d802-userdebug
add_lunch_combo spirit_grouper-userdebug
add_lunch_combo spirit_i9100-userdebug
add_lunch_combo spirit_jflte-userdebug
add_lunch_combo spirit_ks01lte-userdebug
add_lunch_combo spirit_hammerhead-userdebug
